import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

import ThemeProvider from '@/components/theme-provider'
import Navigation from '@/components/navigation'
import Background from '@/components/background'
import Footer from '@/components/footer'
import Chattrbot from '@/components/chattrbot'

export const metadata: Metadata = {
  title: 'Create Chattr App',
  description: 'Generated by create chattr app',
}

export const runtime = 'edge'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={`flex size-full flex-col scroll-smooth ${GeistSans.className} bg-zinc-100 antialiased dark:bg-black`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Navigation />
          <Background />
          <div className='pt-[116px]' />
          <main className='flex-auto'>{children}</main>
          <Chattrbot />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
