import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

import {
  ThemeProvider,
  Background,
  Navigation,
  QuickstartChattrbot,
  Footer,
} from '@/components'

export const metadata: Metadata = {
  title: 'Create Chattr App',
  description: 'Generated by create chattr app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={`flex h-full w-full flex-col scroll-smooth ${GeistSans.className} bg-zinc-100 antialiased dark:bg-black`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Navigation />
          <Background />
          <div className='mt-[116px]'></div>
          <main className='flex-auto'>{children}</main>
          <QuickstartChattrbot />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
